# Generated by Django 5.1 on 2024-08-24 14:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='Note',
        ),
        migrations.RemoveField(
            model_name='note',
            name='receiver',
        ),
        migrations.AddField(
            model_name='note',
            name='recipient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 8, 24, 14, 50, 20, 97246, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
