# Generated by Django 5.1 on 2024-08-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_note_note_remove_note_receiver_note_recipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('disapproved', 'disapproved')], default='pending', max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('disapproved', 'disapproved')], default='pending', max_length=12),
        ),
    ]
