# Generated by Django 5.1 on 2024-09-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_note_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('disapproved', 'disapproved')], default='pending', max_length=12),
        ),
    ]
